### ISSUE TITLE
Missing Database

### ISSUE THREAD

**Issue by phuclu** [medibloc/explorer#1]
When run server start, server report missing data tables.
![image](https://user-images.githubusercontent.com/37874183/48534049-5ff15980-e8d9-11e8-8781-e36a25426c25.png)

**Comment by ggomma** [comment]
Hello. Please check the followings.

1. Did you install mysql successfully?
2. Did you export your database username and password to access?
3. Did you run the latest version of the explorer?

**Comment by phuclu** [comment]
Thanks for your questions:

   1. I install my sql succesfully. I use mysql command to create
   medi_explorer database
   2. Before I create medi_explorer database. It returns error missing
   medi_explorer database. But after that, it return error block table
   missing. So I think the export for username and password is correct.
   3. I use clone command so I think that I use the version in github.

Thanks

**Comment by ggomma** [comment]
That's because mysql doesn't have proper model before executed.

Try `npm run syncdb`
After your mysql database is synced, you are good to go.

**Comment by ggomma** [comment]
Closing issue.
