### ISSUE TITLE
[BUG] TokenInfo Component 언어 변경에 따른 상태 변경

### ISSUE THREAD

**Issue by RyuK-H** [medibloc/explorer#7]
pages/Home.js 의 `TokenInfo` Component는 언어 변경에 따른 상태 변화가 이루어지지 않습니다!

redux에 대한 경험이 없어, 직접 수정하지는 않았지만 혹 도움이 될까 이슈 올립니다.

![MED](https://user-images.githubusercontent.com/20147441/71956515-c1d3f780-322e-11ea-94ff-4da5dedbd884.gif)

**Comment by ggomma** [comment]
안녕하세요. 버그를 찾아주셔서 감사합니다.

현재 Explorer 업그레이드에 관련된 작업을 내부에서 진행하고 있습니다.
향후 새로운 버전의 Explorer가 출시될 예정이기에 말씀주신 Bug는 당장 반영되지 않을 수 있습니다.

감사합니다.
